---
title: "01 Machine Learning Fundamentals"
author: "Ahmed Mahmoud"
date: "2021-1-05"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

# Libraries

Load the following libraries. 


```{r}
# install.packages("plotly")

library(tidyverse)
library(tidyquant)
library(broom)
library(umap)
```


```{r}
# STOCK PRICES
sp_500_prices_tbl <- read_rds("B_ML/sp_500_prices_tbl.rds")
sp_500_prices_tbl
```



```{r}
# SECTOR INFORMATION
sp_500_index_tbl <- read_rds("raw_data/sp_500_index_tbl.rds")
sp_500_index_tbl
```




```{r}
sp_500_daily_returns_tbl <- select(sp_500_prices_tbl, symbol, date, adjusted)%>%
  filter(date >= as.Date("2018-01-01"))%>%
  group_by(symbol)%>%
  mutate(lag = lag(adjusted))%>%
  na.exclude()%>%
  mutate(diff = adjusted - lag)%>%
  mutate(pct_return = diff / lag)%>%
  select(symbol, date, pct_return)%>%
  ungroup()
# Output: sp_500_daily_returns_tbl
```


## Step 2 - Convert to User-Item Format


```{r}
sp_500_daily_returns_tbl <- read_rds("raw_data/sp_500_daily_returns_tbl.rds")
sp_500_daily_returns_tbl
```



```{r}
# Convert to User-Item Format
stock_date_matrix_tbl <- sp_500_daily_returns_tbl%>%
  spread(date, pct_return, fill = 0)%>%
  ungroup()

# Output: stock_date_matrix_tbl
```



## Step 3 - Perform K-Means Clustering

```{r}
stock_date_matrix_tbl <- read_rds("raw_data/stock_date_matrix_tbl.rds")
```


```{r}
# Create kmeans_obj for 4 centers
kmeans_obj <- stock_date_matrix_tbl%>%
  subset(select = -c(symbol))%>%
  kmeans(centers = 4, nstart = 20)

```

Use `glance()` to get the `tot.withinss`. 

```{r}
# Apply glance() to get the tot.withinss
broom::glance(kmeans_obj)

```

## Step 4 - Find the optimal value of K


```{r}
kmeans_mapper <- function(center = 3) {
    stock_date_matrix_tbl %>%
        select(-symbol) %>%
        kmeans(centers = center, nstart = 20)
}
```



```{r}
# Use purrr to map
kmeans_mapped_tbl <- tibble(centers = 1:30)%>%
  mutate(k_means = centers %>% map(kmeans_mapper))%>%
  mutate(glance  = k_means %>% map(glance))


```



```{r}
# Visualize Scree Plot
kmeans_mapped_tbl %>%
  unnest(glance)%>%
  select(centers, tot.withinss)%>%
  
  # visualization
  ggplot(aes(centers, tot.withinss)) +
  geom_point(color = "#2DC6D6", size = 4) +
  geom_line(color = "#2DC6D6", size = 1) +
    
  # Add labels (which are repelled a little)
  ggrepel::geom_label_repel(aes(label = centers), color = "#2DC6D6") + 
      
  # Formatting
  labs(title = "Scree Plot",
  subtitle = "",
  caption = "Conclusion: Based on the Scree Plot, we select 3 clusters to segment the company base.")
```




## Step 5 - Apply UMAP

```{r}
k_means_mapped_tbl <- read_rds("raw_data/k_means_mapped_tbl.rds")
```


```{r}
# Apply UMAP

umap_results <- stock_date_matrix_tbl%>%
  select(-symbol)%>%
  umap()

```



```{r}
# Convert umap results to tibble with symbols
umap_results_tbl <- umap_results$layout%>%
  as_tibble(.name_repair = "unique")%>%
  set_names(c("x", "y"))%>%
    bind_cols(
        stock_date_matrix_tbl %>% select(symbol)
    )


```



```{r}
# Visualize UMAP results

umap_results_tbl %>%
    ggplot(aes(x, y)) +
    geom_point(alpha = 0.5) + 
    labs(title = "UMAP Projection") +
    theme_tq()

```


## Step 6 - Combine K-Means and UMAP

```{r}
k_means_mapped_tbl <- read_rds("raw_data/k_means_mapped_tbl.rds")
umap_results_tbl   <- read_rds("raw_data/umap_results_tbl.rds")
```



```{r}
# Get the k_means_obj from the 10th center

k_means_obj <- kmeans_mapped_tbl %>%
    pull(k_means) %>%
    pluck(10)


```


```{r}
# Use your dplyr & broom skills to combine the k_means_obj with the umap_results_tbl
umap_kmeans_cluster_tbl <- k_means_obj %>% 
    augment(stock_date_matrix_tbl) %>%
    select(symbol, .cluster)
    
  umap_kmeans_results_tbl <- umap_results_tbl %>%
    left_join(umap_kmeans_cluster_tbl, by = "symbol")%>%
    left_join(sp_500_index_tbl %>% select(symbol, company, sector), by = "symbol")

 
```


```{r}
# Visualize the combined K-Means and UMAP results
umap_kmeans_results_tbl %>%
    ggplot(aes(V1,V2,color = .cluster)) +
    geom_point(alpha = 0.5)
```

Congratulations! You are done with the 1st challenge!